<?php
/**
 * InlineResponse20042
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Scubawhere API Documentation
 *
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * InlineResponse20042 Class Doc Comment
 *
 * @category    Class */
/** 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse20042 implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'inline_response_200_42';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'daterange' => '\Swagger\Client\Model\DateRange',
        'utilisation' => '\Swagger\Client\Model\InlineResponse20042Utilisation',
        'utilisation_totals' => '\Swagger\Client\Model\InlineResponse20042UtilisationTotals'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'daterange' => 'daterange',
        'utilisation' => 'utilisation',
        'utilisation_totals' => 'utilisation_totals'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'daterange' => 'setDaterange',
        'utilisation' => 'setUtilisation',
        'utilisation_totals' => 'setUtilisationTotals'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'daterange' => 'getDaterange',
        'utilisation' => 'getUtilisation',
        'utilisation_totals' => 'getUtilisationTotals'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['daterange'] = isset($data['daterange']) ? $data['daterange'] : null;
        $this->container['utilisation'] = isset($data['utilisation']) ? $data['utilisation'] : null;
        $this->container['utilisation_totals'] = isset($data['utilisation_totals']) ? $data['utilisation_totals'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        return true;
    }


    /**
     * Gets daterange
     * @return \Swagger\Client\Model\DateRange
     */
    public function getDaterange()
    {
        return $this->container['daterange'];
    }

    /**
     * Sets daterange
     * @param \Swagger\Client\Model\DateRange $daterange
     * @return $this
     */
    public function setDaterange($daterange)
    {
        $this->container['daterange'] = $daterange;

        return $this;
    }

    /**
     * Gets utilisation
     * @return \Swagger\Client\Model\InlineResponse20042Utilisation
     */
    public function getUtilisation()
    {
        return $this->container['utilisation'];
    }

    /**
     * Sets utilisation
     * @param \Swagger\Client\Model\InlineResponse20042Utilisation $utilisation
     * @return $this
     */
    public function setUtilisation($utilisation)
    {
        $this->container['utilisation'] = $utilisation;

        return $this;
    }

    /**
     * Gets utilisation_totals
     * @return \Swagger\Client\Model\InlineResponse20042UtilisationTotals
     */
    public function getUtilisationTotals()
    {
        return $this->container['utilisation_totals'];
    }

    /**
     * Sets utilisation_totals
     * @param \Swagger\Client\Model\InlineResponse20042UtilisationTotals $utilisation_totals
     * @return $this
     */
    public function setUtilisationTotals($utilisation_totals)
    {
        $this->container['utilisation_totals'] = $utilisation_totals;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


