<?php
/**
 * InlineResponse20040
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Scubawhere API Documentation
 *
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * InlineResponse20040 Class Doc Comment
 *
 * @category    Class */
/** 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse20040 implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'inline_response_200_40';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'daterange' => '\Swagger\Client\Model\DateRange',
        'accommodations' => '\Swagger\Client\Model\ReportEntry',
        'accommodation_toal' => '\Swagger\Client\Model\ReportEntryTotal',
        'addons' => '\Swagger\Client\Model\ReportEntry',
        'addons_toal' => '\Swagger\Client\Model\ReportEntryTotal',
        'courses' => '\Swagger\Client\Model\ReportEntry',
        'courses_toal' => '\Swagger\Client\Model\ReportEntryTotal',
        'fees' => '\Swagger\Client\Model\ReportEntry',
        'fees_toal' => '\Swagger\Client\Model\ReportEntryTotal',
        'packages' => '\Swagger\Client\Model\ReportEntry',
        'package_toal' => '\Swagger\Client\Model\ReportEntryTotal',
        'tickets' => '\Swagger\Client\Model\ReportEntry',
        'ticket_toal' => '\Swagger\Client\Model\ReportEntryTotal'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'daterange' => 'daterange',
        'accommodations' => 'accommodations',
        'accommodation_toal' => 'accommodation_toal',
        'addons' => 'addons',
        'addons_toal' => 'addons_toal',
        'courses' => 'courses',
        'courses_toal' => 'courses_toal',
        'fees' => 'fees',
        'fees_toal' => 'fees_toal',
        'packages' => 'packages',
        'package_toal' => 'package_toal',
        'tickets' => 'tickets',
        'ticket_toal' => 'ticket_toal'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'daterange' => 'setDaterange',
        'accommodations' => 'setAccommodations',
        'accommodation_toal' => 'setAccommodationToal',
        'addons' => 'setAddons',
        'addons_toal' => 'setAddonsToal',
        'courses' => 'setCourses',
        'courses_toal' => 'setCoursesToal',
        'fees' => 'setFees',
        'fees_toal' => 'setFeesToal',
        'packages' => 'setPackages',
        'package_toal' => 'setPackageToal',
        'tickets' => 'setTickets',
        'ticket_toal' => 'setTicketToal'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'daterange' => 'getDaterange',
        'accommodations' => 'getAccommodations',
        'accommodation_toal' => 'getAccommodationToal',
        'addons' => 'getAddons',
        'addons_toal' => 'getAddonsToal',
        'courses' => 'getCourses',
        'courses_toal' => 'getCoursesToal',
        'fees' => 'getFees',
        'fees_toal' => 'getFeesToal',
        'packages' => 'getPackages',
        'package_toal' => 'getPackageToal',
        'tickets' => 'getTickets',
        'ticket_toal' => 'getTicketToal'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['daterange'] = isset($data['daterange']) ? $data['daterange'] : null;
        $this->container['accommodations'] = isset($data['accommodations']) ? $data['accommodations'] : null;
        $this->container['accommodation_toal'] = isset($data['accommodation_toal']) ? $data['accommodation_toal'] : null;
        $this->container['addons'] = isset($data['addons']) ? $data['addons'] : null;
        $this->container['addons_toal'] = isset($data['addons_toal']) ? $data['addons_toal'] : null;
        $this->container['courses'] = isset($data['courses']) ? $data['courses'] : null;
        $this->container['courses_toal'] = isset($data['courses_toal']) ? $data['courses_toal'] : null;
        $this->container['fees'] = isset($data['fees']) ? $data['fees'] : null;
        $this->container['fees_toal'] = isset($data['fees_toal']) ? $data['fees_toal'] : null;
        $this->container['packages'] = isset($data['packages']) ? $data['packages'] : null;
        $this->container['package_toal'] = isset($data['package_toal']) ? $data['package_toal'] : null;
        $this->container['tickets'] = isset($data['tickets']) ? $data['tickets'] : null;
        $this->container['ticket_toal'] = isset($data['ticket_toal']) ? $data['ticket_toal'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        return true;
    }


    /**
     * Gets daterange
     * @return \Swagger\Client\Model\DateRange
     */
    public function getDaterange()
    {
        return $this->container['daterange'];
    }

    /**
     * Sets daterange
     * @param \Swagger\Client\Model\DateRange $daterange
     * @return $this
     */
    public function setDaterange($daterange)
    {
        $this->container['daterange'] = $daterange;

        return $this;
    }

    /**
     * Gets accommodations
     * @return \Swagger\Client\Model\ReportEntry
     */
    public function getAccommodations()
    {
        return $this->container['accommodations'];
    }

    /**
     * Sets accommodations
     * @param \Swagger\Client\Model\ReportEntry $accommodations
     * @return $this
     */
    public function setAccommodations($accommodations)
    {
        $this->container['accommodations'] = $accommodations;

        return $this;
    }

    /**
     * Gets accommodation_toal
     * @return \Swagger\Client\Model\ReportEntryTotal
     */
    public function getAccommodationToal()
    {
        return $this->container['accommodation_toal'];
    }

    /**
     * Sets accommodation_toal
     * @param \Swagger\Client\Model\ReportEntryTotal $accommodation_toal
     * @return $this
     */
    public function setAccommodationToal($accommodation_toal)
    {
        $this->container['accommodation_toal'] = $accommodation_toal;

        return $this;
    }

    /**
     * Gets addons
     * @return \Swagger\Client\Model\ReportEntry
     */
    public function getAddons()
    {
        return $this->container['addons'];
    }

    /**
     * Sets addons
     * @param \Swagger\Client\Model\ReportEntry $addons
     * @return $this
     */
    public function setAddons($addons)
    {
        $this->container['addons'] = $addons;

        return $this;
    }

    /**
     * Gets addons_toal
     * @return \Swagger\Client\Model\ReportEntryTotal
     */
    public function getAddonsToal()
    {
        return $this->container['addons_toal'];
    }

    /**
     * Sets addons_toal
     * @param \Swagger\Client\Model\ReportEntryTotal $addons_toal
     * @return $this
     */
    public function setAddonsToal($addons_toal)
    {
        $this->container['addons_toal'] = $addons_toal;

        return $this;
    }

    /**
     * Gets courses
     * @return \Swagger\Client\Model\ReportEntry
     */
    public function getCourses()
    {
        return $this->container['courses'];
    }

    /**
     * Sets courses
     * @param \Swagger\Client\Model\ReportEntry $courses
     * @return $this
     */
    public function setCourses($courses)
    {
        $this->container['courses'] = $courses;

        return $this;
    }

    /**
     * Gets courses_toal
     * @return \Swagger\Client\Model\ReportEntryTotal
     */
    public function getCoursesToal()
    {
        return $this->container['courses_toal'];
    }

    /**
     * Sets courses_toal
     * @param \Swagger\Client\Model\ReportEntryTotal $courses_toal
     * @return $this
     */
    public function setCoursesToal($courses_toal)
    {
        $this->container['courses_toal'] = $courses_toal;

        return $this;
    }

    /**
     * Gets fees
     * @return \Swagger\Client\Model\ReportEntry
     */
    public function getFees()
    {
        return $this->container['fees'];
    }

    /**
     * Sets fees
     * @param \Swagger\Client\Model\ReportEntry $fees
     * @return $this
     */
    public function setFees($fees)
    {
        $this->container['fees'] = $fees;

        return $this;
    }

    /**
     * Gets fees_toal
     * @return \Swagger\Client\Model\ReportEntryTotal
     */
    public function getFeesToal()
    {
        return $this->container['fees_toal'];
    }

    /**
     * Sets fees_toal
     * @param \Swagger\Client\Model\ReportEntryTotal $fees_toal
     * @return $this
     */
    public function setFeesToal($fees_toal)
    {
        $this->container['fees_toal'] = $fees_toal;

        return $this;
    }

    /**
     * Gets packages
     * @return \Swagger\Client\Model\ReportEntry
     */
    public function getPackages()
    {
        return $this->container['packages'];
    }

    /**
     * Sets packages
     * @param \Swagger\Client\Model\ReportEntry $packages
     * @return $this
     */
    public function setPackages($packages)
    {
        $this->container['packages'] = $packages;

        return $this;
    }

    /**
     * Gets package_toal
     * @return \Swagger\Client\Model\ReportEntryTotal
     */
    public function getPackageToal()
    {
        return $this->container['package_toal'];
    }

    /**
     * Sets package_toal
     * @param \Swagger\Client\Model\ReportEntryTotal $package_toal
     * @return $this
     */
    public function setPackageToal($package_toal)
    {
        $this->container['package_toal'] = $package_toal;

        return $this;
    }

    /**
     * Gets tickets
     * @return \Swagger\Client\Model\ReportEntry
     */
    public function getTickets()
    {
        return $this->container['tickets'];
    }

    /**
     * Sets tickets
     * @param \Swagger\Client\Model\ReportEntry $tickets
     * @return $this
     */
    public function setTickets($tickets)
    {
        $this->container['tickets'] = $tickets;

        return $this;
    }

    /**
     * Gets ticket_toal
     * @return \Swagger\Client\Model\ReportEntryTotal
     */
    public function getTicketToal()
    {
        return $this->container['ticket_toal'];
    }

    /**
     * Sets ticket_toal
     * @param \Swagger\Client\Model\ReportEntryTotal $ticket_toal
     * @return $this
     */
    public function setTicketToal($ticket_toal)
    {
        $this->container['ticket_toal'] = $ticket_toal;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


