<?php
/**
 * BookingTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Scubawhere API Documentation
 *
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * BookingTest Class Doc Comment
 *
 * @category    Class */
// * @description Booking
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BookingTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Booking"
     */
    public function testBooking()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "reference"
     */
    public function testPropertyReference()
    {

    }

    /**
     * Test attribute "lead_customer_id"
     */
    public function testPropertyLeadCustomerId()
    {

    }

    /**
     * Test attribute "agent_id"
     */
    public function testPropertyAgentId()
    {

    }

    /**
     * Test attribute "agent_reference"
     */
    public function testPropertyAgentReference()
    {

    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {

    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {

    }

    /**
     * Test attribute "discount"
     */
    public function testPropertyDiscount()
    {

    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {

    }

    /**
     * Test attribute "reserved_until"
     */
    public function testPropertyReservedUntil()
    {

    }

    /**
     * Test attribute "cancellation_fee"
     */
    public function testPropertyCancellationFee()
    {

    }

    /**
     * Test attribute "comment"
     */
    public function testPropertyComment()
    {

    }

    /**
     * Test attribute "parent_id"
     */
    public function testPropertyParentId()
    {

    }

    /**
     * Test attribute "decimal_price"
     */
    public function testPropertyDecimalPrice()
    {

    }

    /**
     * Test attribute "real_decimal_price"
     */
    public function testPropertyRealDecimalPrice()
    {

    }

    /**
     * Test attribute "arrival_date"
     */
    public function testPropertyArrivalDate()
    {

    }

    /**
     * Test attribute "created_at_local"
     */
    public function testPropertyCreatedAtLocal()
    {

    }

    /**
     * Test attribute "lead_customer"
     */
    public function testPropertyLeadCustomer()
    {

    }

    /**
     * Test attribute "payments"
     */
    public function testPropertyPayments()
    {

    }

    /**
     * Test attribute "refunds"
     */
    public function testPropertyRefunds()
    {

    }

}
